insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:30',0,'Below Detection',936,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:15',0,'Below Detection',937,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:40',0,'Below Detection',938,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',0,'Below Detection',939,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',0,'Below Detection',940,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('14:15',0,'Below Detection',941,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:30',222,null,942,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',0,'Below Detection',943,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:15',0,'Below Detection',944,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:30',0,'Below Detection',945,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:15',0,'Below Detection',1019,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:15',0,'Below Detection',946,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',0,'Below Detection',947,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('8:30',0,'Below Detection',948,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:30',0,'Below Detection',949,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('14:30',0,'Below Detection',950,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',0,'Below Detection',951,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',0,'Below Detection',952,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:45',0,'Below Detection',953,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:15',0,'Below Detection',954,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('8:10',0,'Below Detection',955,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:00',0,'Below Detection',956,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',0,'Below Detection',957,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:15',0,'Below Detection',958,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:30',0,'Below Detection',959,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:15',0,'Below Detection',960,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:15',0,'Below Detection',961,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('17:30',0,'Below Detection',962,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',0,'Below Detection',963,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',0,'Below Detection',1020,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:30',0,'Below Detection',964,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:30',0,'Below Detection',965,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:00',0,'Below Detection',966,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',0,'Below Detection',967,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:30',0,'Below Detection',968,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values (null,0,'Below Detection',969,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',0,'Below Detection',971,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:15',354,null,972,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:00',0,'Below Detection',973,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:00',0,'Below Detection',974,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:45',0,'Below Detection',975,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:00',112,null,976,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',83,null,977,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',54,null,978,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:15',143,null,979,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:15',83,null,980,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:45',134,null,981,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:00',134,null,982,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',134,null,983,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:45',199,null,984,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:30',354,null,985,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',779,null,986,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:15',779,null,987,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:45',894,null,988,2);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:30',4000,null,989,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:15',5000,null,990,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',4500,null,991,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('16:15',8000,null,992,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:45',5000,null,993,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:30',7000,null,994,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('14:00',6000,null,995,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',7000,null,996,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',9000,null,997,4);
insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:15',4000,null,998,4);




-- Already in database
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:15',12000,null,999,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:00',20000,null,1002,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:30',17000,null,1003,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:00',20000,null,1004,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('14:00',23000,null,1005,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:00',15000,null,1006,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('9:45',20000,null,1007,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('11:30',7500,null,1008,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values (null,8500,null,1009,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',20000,null,1010,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('13:30',17000,null,1011,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:00',17000,null,1012,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:45',15000,null,1013,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:45',15000,null,1014,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:45',27000,null,1021,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:30',27000,null,1015,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('12:30',18000,null,1016,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:30',22000,null,1017,4);
-- insert into riverlife.standardized_salinity ( salinity_time, total_salinity_ppm, notes, site_sampling_id, salinity_method_id) values ('10:45',26000,null,1018,4);