insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (104,1,32,20);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (107,2,60,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (107,2,70,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (107,2,69,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (101,1,32,46);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (101,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (101,1,60,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (101,1,69,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (100,2,46,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (72,3,37,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (71,1,9,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (71,1,32,33);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (71,1,37,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (71,1,50,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (91,1,72,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (91,1,32,133);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (91,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (91,1,54,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (86,1,28,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (86,1,32,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (86,1,36,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (67,1,32,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (66,1,3,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (66,1,4,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (66,1,32,10);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (65,1,32,132);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (65,1,37,15);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (64,1,9,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (64,1,32,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (64,1,36,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (64,1,37,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (63,1,32,43);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (63,1,34,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (63,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (63,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (63,1,50,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (62,1,32,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (62,1,37,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (62,1,62,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (62,1,69,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (61,1,9,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (61,1,32,235);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (61,1,36,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (61,1,37,20);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (61,1,50,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (60,1,28,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (60,1,32,30);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (60,1,34,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (60,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (60,1,37,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (57,1,32,8);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (57,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,32,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,34,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,37,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,50,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (55,1,58,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (54,1,27,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,3,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,9,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,32,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,36,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,37,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (52,1,50,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (51,1,32,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (51,1,37,8);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (51,1,62,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (51,1,69,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (50,1,1,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (50,1,32,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (50,1,34,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (50,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (49,1,12,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (49,1,32,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (49,1,37,95);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (49,1,48,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (48,1,16,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (48,1,28,15);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (48,1,32,23);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (48,1,36,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (48,1,37,22);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,1,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,3,100);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,36,12);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,37,10);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,48,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,62,9);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (46,1,69,9);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,16,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,19,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,36,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,39,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,41,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,46,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,47,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,58,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,62,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (44,1,69,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,3,15);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,6,15);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,16,18);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,27,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,36,9);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (43,1,37,15);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (42,1,3,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (42,1,16,8);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (42,1,37,4);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (42,1,46,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,3,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,6,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,9,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,12,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,37,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (115,1,48,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,3,67);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,7,67);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,16,20);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,27,16);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,36,3);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,37,4);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,39,13);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,41,9);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,42,4);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,46,11);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (41,1,47,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (40,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (40,1,46,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (40,1,48,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (40,1,54,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,3,10);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,4,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,6,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,7,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,27,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,39,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,41,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,42,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (38,1,50,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,9,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,13,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,16,14);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,17,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,27,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,37,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,39,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,45,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,67,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,46,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (37,1,48,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,3,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,4,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,13,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,16,11);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,36,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,37,3);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,39,3);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,41,3);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,46,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,47,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,52,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (36,1,54,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,16,13);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,39,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,41,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (34,1,50,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,3,238);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,5,14);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,16,33);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,37,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,39,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,42,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (32,1,54,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,3,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,6,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,16,10);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,37,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,39,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,41,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (30,1,43,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,1,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,10,25);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,16,37);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,27,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,39,55);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,40,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,41,16);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,42,36);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,46,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (29,1,47,7);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,10,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,16,2);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,17,22);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,27,13);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,39,14);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,43,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,46,1);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (28,1,47,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,3,8);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,4,8);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,37,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,39,14);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,41,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (26,1,42,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,3,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,5,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,13,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,16,14);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,27,102);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,28,19);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,36,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,39,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,41,10);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,42,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,45,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (25,1,46,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,10,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,12,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,16,21);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,19,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,22,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,37,20);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,39,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,42,12);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,46,21);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,47,21);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,48,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,62,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (24,1,69,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,3,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,5,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,16,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,36,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,39,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,41,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,42,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (21,1,46,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,16,17);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,17,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,36,16);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,46,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (19,1,47,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,3,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,13,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,16,175);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,27,41);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,39,21);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,41,11);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,42,10);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,46,16);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (17,1,47,16);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,9,4);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,16,139);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,27,518);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,28,12);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,36,16);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,39,44);
-- insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (15,1,42,44);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,12,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,27,62);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,37,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,39,7);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,40,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (13,1,41,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (12,1,16,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (12,1,28,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (10,1,19,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (10,1,23,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (10,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (130,1,16,6);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,27,3);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,30,8);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,37,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,39,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,41,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (8,1,48,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (4,1,16,1);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (4,1,27,2);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (3,1,16,4);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (3,1,39,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (3,1,42,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (2,1,16,122);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (2,1,27,75);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (2,1,46,5);
insert into riverlife.site_sampling_fish_count ( site_sampling_id, fishing_method_id, fish_id, amount) values (1,1,15,15);
